### ISSUE TITLE
Perl version out of date

### ISSUE THREAD

**Issue by suziqlib** [jehandzlik/Manatee#1]
I've noticed a lot of errors when I try to run this software.  It appears to stem from an update to perl that alters the usage of hotkeys. Is there a fix for this?  Thanks!

**Comment by jehandzlik** [comment]
Hi!

Thanks for the comment. I have uploaded the new Manatee version tested on Perl v5.18.2 and v5.30.1..

Joanna

**Comment by jehandzlik** [comment]
Hi!

Thanks for the comment. I have uploaded the new Manatee version tested on Perl v5.18.2 and v5.30.1..

Joanna

**Comment by suziqlib** [comment]
Thanks for getting back to me. Whenever I try to run the software, with or
without the config file, I get this error:

Experimental keys on scalar is now forbidden at ./manatee line 458.

Type of arg 1 to keys must be hash or array (not hash element) at ./manatee
line 458, near "})"

Experimental keys on scalar is now forbidden at ./manatee line 556.

Type of arg 1 to keys must be hash or array (not hash element) at ./manatee
line 556, near "})"

Experimental keys on scalar is now forbidden at ./manatee line 561.

Type of arg 1 to keys must be hash or array (not hash element) at ./manatee
line 561, near "})"

Experimental keys on scalar is now forbidden at ./manatee line 629.

Type of arg 1 to keys must be hash or array (not hash element) at ./manatee
line 629, near "})"

Experimental keys on scalar is now forbidden at ./manatee line 630.

Type of arg 1 to keys must be hash or array (not hash element) at ./manatee
line 630, near "}) "

./manatee has too many errors.

**Comment by jehandzlik** [comment]
Have you used the updated version of Manatee? On my end it works fine with the newest Perl version.

**Comment by suziqlib** [comment]
I downloaded the version on github a couple weeks ago.

**Comment by suziqlib** [comment]
Have you seen the previous email?

**Comment by jehandzlik** [comment]
Hi,

You should download Manatee once again. The code has changed since the last time you downloaded it. 

Best,

Joanna

**Comment by suziqlib** [comment]
Looks great so far. Thanks for your help!

**Comment by suziqlib** [comment]
Hello!
The cluster output appears fine, but there seems to be a problem with the
count matrix output.  I see a lot of warning messages pertaining to the GFF
file:

Use of uninitialized value $gene_id in concatenation (.) or string at
./manatee line 1885, <ANNOTATION_FILE> line 39.

Use of uninitialized value $gene_biotype in concatenation (.) or string at
./manatee line 1885, <ANNOTATION_FILE> line 39.

Use of uninitialized value $gene_name in concatenation (.) or string at
./manatee line 1885, <ANNOTATION_FILE> line 39.

Use of uninitialized value $gene_name in hash element at ./manatee line
1891, <ANNOTATION_FILE> line 39.
I haven't used a transcriptome matrix as an input.  What type of
transcriptome matrix is used as an input? Does it incorporate the fastq
file or is it based solely on the GFF? Could I make a transcriptome index
with tophat? The transcriptome index file that manatee generated was
deleted after it ran, and the file appeared empty while it was running.
I'm not sure what happened.  Thanks!

**Comment by jehandzlik** [comment]
Hi!

Are you using your own annotation file? The annotation needs to be in a GTF format with the following tags in the attributes field: gene_name, gene_id, and gene_biotype. In the "annotation" branch you can find an example file for human non-coding annotation in hg38 version. What I suspect happens here is that the annotation file you are using is in inappropriate for Manatee format. Once you provide the annotation in a proper format, the transcriptome index will be generated for you in the trans-index directory in the manatee folder. 

Example of annotation line in GTF format:
chr18	.	.	47380503	47380524	.	+	.	gene_id "MIMAT0019066"; gene_name "hsa-miR-4527"; gene_biotype "miRNA";

**Comment by carolcorreia** [comment]
Hi @jehandzlik,

Did the GTF format example you used above come from Ensembl?
Would you plan adding support for miRBase gff3 annotation files in the future?

Thanks!

**Comment by jehandzlik** [comment]
Hi Carolina,

The annotation included in the 'annotation' branch was based on sncRNAs derived from Ensemble v85, GtRNAdb, and miRBase v21.
I was planning on containerizing the Manatee project soon and when doing so I could try adding the gff3 format as well. Thanks!

Joanna
