### ISSUE TITLE
Cannot find test data

### ISSUE THREAD

**Issue by ntbeileh** [jehandzlik/Manatee#9]
I wanted to run on the simulated dataset linked in the Nature paper but the link does not work, https://github.com/jehandzlik/Manatee/tree/master/simulated_data

Where can I find this data?

**Comment by jehandzlik** [comment]
Hi,

Simulated data is available in the "simulatedData" branch. Link to the simulated data: https://github.com/jehandzlik/Manatee/tree/simulatedData

Best,
Joanna

**Comment by ntbeileh** [comment]
Thank you!
